"""create stock portfolios and holdings

Revision ID: 4c4dccb8d9ff
Revises: 9a84eaf88dd2
Create Date: 2026-08-10 17:03:44.617640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4dccb8d9ff'
down_revision: Union[str, Sequence[str], None] = '9a84eaf88dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_portfolio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uniq_user_name')
    )
    op.create_index(op.f('ix_stocks_portfolio_user_id'), 'stocks_portfolio', ['user_id'], unique=False)
    op.create_table('stocks_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchange'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('buy_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['stocks_portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', 'exchange', name='uq_stock_holding_portfolio_ticker_exchange')
    )
    op.create_index(op.f('ix_stocks_holdings_portfolio_id'), 'stocks_holdings', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_holdings_portfolio_id'), table_name='stocks_holdings')
    op.drop_table('stocks_holdings')
    op.drop_index(op.f('ix_stocks_portfolio_user_id'), table_name='stocks_portfolio')
    op.drop_table('stocks_portfolio')
    # ### end Alembic commands ###
