"""add avatar_id notifications_enabled

Revision ID: b7721f3176ce
Revises: 71c3fc44c8c1
Create Date: 2026-08-20 14:12:38.464151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7721f3176ce'
down_revision: Union[str, Sequence[str], None] = '71c3fc44c8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', sa.String(length=50), nullable=False, server_default='avatar_01'))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
